image: jonaskello/docker-and-compose:1.12.1-1.8.0

services:
  - docker:1.12.1-dind

before_script:
  - docker info

build:
  stage: build
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker-compose -f docker-compose.test.yml up sut
