image: docker:17.03.1-ce

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build
  - deploy

test:
  stage: build
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose

    - docker-compose -f docker-compose.test.yml build sut
    - docker-compose -f docker-compose.test.yml up sut

build:
  stage: build
  variables:
    IMAGE_TAG_BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    IMAGE_TAG_HASH: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

  script:

    - docker build -f Dockerfile -t $IMAGE_TAG_HASH .
    - docker push $IMAGE_TAG_HASH

    - docker build -f Dockerfile -t $IMAGE_TAG_BRANCH .
    - docker push $IMAGE_TAG_BRANCH

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo 'DEPLOY HERE'
