image: docker:stable

services:
  - docker:dind

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE:master || true
    - docker build --cache-from $CONTAINER_IMAGE:master --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG


deploy:
  stage: deploy
  only:
    - master
  script:
    - docker pull $CONTAINER_IMAGE:master
    - docker build --cache-from $CONTAINER_IMAGE:master --tag $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:latest
