image: docker:stable

services:
  - docker:dind

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

before_script:

stages:
  - build
  - deploy

rubocop:
  stage: build
  image: ruby
  script:
    - gem install rubocop -v '0.57.2'
    - rubocop

audit:
  stage: build
  image: ruby
  script:
    - gem install bundler-audit
    - bundle-audit check --update

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_PIPELINE_IID --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID  --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CONTAINER_IMAGE:$CI_PIPELINE_IID
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME

build-dev:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_IMAGE:latest-dev || true
    - docker build --cache-from $CONTAINER_IMAGE:latest-dev --tag $CONTAINER_IMAGE:$CI_PIPELINE_IID-dev --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID-dev --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME-dev .
    - docker push $CONTAINER_IMAGE:$CI_PIPELINE_IID-dev
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID-dev
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME-dev

latest:
  stage: deploy
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_IMAGE:$CI_PIPELINE_IID
    - docker build --cache-from $CONTAINER_IMAGE:$CI_PIPELINE_IID --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:latest

latest-dev:
  stage: deploy
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_IMAGE:$CI_PIPELINE_IID-dev
    - docker build --cache-from $CONTAINER_IMAGE:$CI_PIPELINE_IID-dev --tag $CONTAINER_IMAGE:latest-dev -f Dockerfile.dev .
    - docker push $CONTAINER_IMAGE:latest-dev
