inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
FrozenStringLiteralComment:
  Enabled: false
