db:
  image: postgres:9.4.5

memcached:
  image: memcached:1.4.27-alpine

redis:
  image: redis:3.2.1-alpine

web:
  build: .
  ports:
    - "80:3000"
  links: 
    - db
    - memcached
    - redis
  env_file:
    - .env
  environment:
    - RAILS_ENV=development
  volumes:
    - /home/app/mazavr/public/sitemaps

worker:
  build: .
  links: 
    - db
    - memcached
    - redis
  command: bin/worker
  environment:
    - RAILS_ENV=development
  env_file:
    - .env
  volumes_from:
    - web

backup:
  build: containers/backup
  links: 
    - db
  env_file:
    - .env.pg-backup
