db:
  image: postgres:9.4.5

memcached:
  image: memcached:1.4.27-alpine

redis:
  image: redis:3.2.1-alpine

web:
  build: .
  ports:
    - "3000:3000"
  links: 
    - db
    - memcached
    - redis
  env_file:
    - .env
  environment:
    - RAILS_ENV=development
    - PASSENGER_APP_ENV=development
  volumes:
    - ./:/home/app/mazavr
  command: bin/webrick

worker:
  build: .
  links: 
    - db
    - memcached
    - redis
  command: bin/worker
  env_file:
    - .env
  environment:
    - RAILS_ENV=development
  volumes:
    - ./:/home/app/mazavr

backup:
  build: containers/backup
  links: 
    - db
  env_file:
    - .env.pg-backup
