db:
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"

memcached:
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"

web:
  ports:
    - "81:3000"
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"
  environment:
    - RAILS_ENV=production
