db:
  image: postgres:9.4.5

memcached:
  image: memcached:1.4.27-alpine

redis:
  image: redis:3.2.1-alpine

web:
  build: .
  ports:
    - "3000:3000"
  links: 
    - db
    - memcached
    - redis
    - backup-service
  env_file:
    - .env

worker:
  build: .
  links: 
    - db
    - memcached
    - redis
  command: bundle exec sidekiq
  env_file:
    - .env
  volumes_from:
    - web

backup-service:
  image: russianpulse/pg-backup
  links: 
    - db
  env_file:
    - .env.pg-backup
