db:
  image: postgres:9.4.5

memcached:
  image: memcached:1.4.27-alpine

redis:
  image: redis:3.2.1-alpine

# Docker test service
sut:
  build: .
  links: 
    - db
    - memcached
    - redis
  environment:
    - RAILS_ENV=test
    - CODECLIMATE_REPO_TOKEN={$CODECLIMATE_REPO_TOKEN}
  env_file:
    - .env.test
  volumes:
    - ./:/app
  command:
    ./bin/test
