db:
  image: postgres:9.4.5

memcached:
  image: memcached:1.4.27

redis:
  image: redis:3.2.3

# Docker test service
sut:
  build: .
  links: 
    - db
    - memcached
    - redis
  environment:
    - RAILS_ENV=test
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN
  env_file:
    - .env.test
  command:
    ./bin/test
