db:
  image: postgres:9.4.5
  restart: unless-stopped

memcached:
  image: memcached:1.4.27
  restart: unless-stopped

redis:
  image: redis:3.2.3
  restart: unless-stopped

web:
  build: .
  restart: unless-stopped
  ports:
    - "3000:80"
  links: 
    - db
    - memcached
    - redis
  env_file:
    - .env
  environment:
    - RAILS_ENV=production
    - DATABASE_URL=postgresql://postgres:postgres@db/production
    - RAILS_MAX_THREADS=16

worker:
  build: .
  restart: unless-stopped
  links: 
    - db
    - memcached
    - redis
  command: worker
  environment:
    - RAILS_ENV=production
    - DATABASE_URL=postgresql://postgres:postgres@db/production
  env_file:
    - .env
