FROM ruby:2.3-slim
WORKDIR /app

RUN apt-get update -qq && apt-get install -y libxml2-dev libxslt1-dev \
      libsqlite3-dev libpq-dev build-essential curl gnupg libfontconfig

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update -qq && apt-get install -y nodejs
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y yarn


RUN apt-get update -qq && apt-get install -y wget
RUN wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O /tmp/phantom.tar.bz2
RUN cd /tmp && tar -xvf phantom.tar.bz2 && mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/

ADD Gemfile* ./
RUN bundle install -j $(nproc) --path /vendor

COPY . ./

COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["web"]
