version: '3'

services:
  site.local:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - webnet
    depends_on:
      - db
      - memcached
      - redis
      - webdriver-firefox
    env_file:
      - .env.test
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@db/test
      - MEMCACHED_URL=memcached
      - RAILS_MAX_THREADS=16
      - CAPYBARA_DRIVER=firefox
    command: "spec"
    volumes:
      - "./:/app"
      - "./volumes/vendor:/vendor"

  db:
    image: postgres:9-alpine
    networks:
      - webnet
    environment:
      - POSTGRES_DB=test

  memcached:
    image: memcached:alpine
    networks:
      - webnet

  redis:
    image: redis:alpine
    networks:
      - webnet

  webdriver-firefox:
    image: selenium/standalone-firefox:3
    networks:
      - webnet

networks:
  webnet:
