version: '3'

services:
  app:
    image: test-image
    networks:
      main:
        aliases:
          - foobar.com
    depends_on:
      - db
      - memcached
      - redis
    env_file:
      - .env.test
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@db/test
      - MEMCACHED_URL=memcached
      - RAILS_MAX_THREADS=16
      - CAPYBARA_DRIVER=firefox
    command: "spec"

  db:
    image: postgres:9-alpine
    networks:
      - main
    environment:
      - POSTGRES_DB=test

  memcached:
    image: memcached:alpine
    networks:
      - main

  redis:
    image: redis:alpine
    networks:
      - main

networks:
  main:

