db:
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"

memcached:
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"

web:
  ports:
    - "80:3000"
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"
  environment:
    - RAILS_ENV=production
  mem_limit: 500000000
  memswap_limit: 500000000

worker:
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"
  environment:
    - RAILS_ENV=production
  mem_limit: 350000000
  memswap_limit: 700000000 # 350 mb of swap is allowed
