db:
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"
  mem_limit: 250000000 # 250 Mb
  memswap_limit: 250000000 # no swap

memcached:
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"
  restart: always
  mem_limit: 100000000 # 100 Mb
  memswap_limit: 100000000 # no swap

redis:
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"

web:
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"
  mem_limit: 500000000 # 500 Mb
  memswap_limit: 500000000 # no swap
  environment:
    - RAILS_ENV=production
  volumes:
    - ./tmp/sitemaps:/sitemaps

worker:
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"
  mem_limit: 250000000 # 250 Mb
  memswap_limit: 500000000 # + 250mb swap
  environment:
    - RAILS_ENV=production

backup:
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "7"
