db:
  image: postgres:9.4.5

memcached:
  image: memcached:1.4.27

redis:
  image: redis:3.2.3

# Docker test service
sut:
  build: .
  links: 
    - db
    - memcached
    - redis
  environment:
    - RAILS_ENV=test
    - DATABASE_URL=postgresql://postgres:postgres@db/test
  env_file:
    - .env.test
  command:
    test
