blogs_update:
  cron: "* * * * *"
  class: CronJobRunner
  args: ['UpdateBlogJob', []]

update_rating:
  cron: "*/15 * * * *"
  class: CronJobRunner
  args: ['UpdateRatingJob', []]

update_posts_per_hour:
  cron: "0 * * * *"
  class: CronJobRunner
  args: ['UpdatePostsPerHourJob', []]

update_top:
  cron: "5 * * * *"
  class: CronJobRunner
  args: ['TopPostsSpiderJob', []]

update_top:
  cron: "5 0 * * *"
  class: CronJobRunner
  args: ['TopPostsSpiderJob', ["all"]]

cleanup:
  cron: "0 */3 * * *"
  class: CronJobRunner
  args: ['CleanupJob', []]

tags_cleanup:
  cron: "15 */3 * * *"
  class: CronJobRunner
  args: ['TagsCleanupJob', []]

